[package]
name = "big"
version = "0.3.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.3", default-features = false, features = ["glow", "wayland"] }
egui = { version = "0.33.3", features = ["serde"] }
egui-phosphor = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
uuid = { version = "1.19.0", features = ["serde", "v4"] }
egui-file-dialog = "0.12.0"
egui_extras = { version = "0.33.3", features = ["file", "gif", "image", "webp"] }
image = { version = "0.25", features = ["jpeg", "png"] }
bpaf = { version = "0.9.22", features = ["derive"] }
twox-hash = { version = "2.1.2", features = ["serialize"] }
walkdir = "2.5.0"
memmap2 = "0.9.9"
pathdiff = "0.2.3"
imagesize = "0.14.0"
dirs = "6.0.0"
guillotiere = "0.6.2"

# use this version which supports ffmpeg 8
video-rs = { git = "https://github.com/oddity-ai/video-rs", rev = "6caba4d08fc11e845bb29bd22594ca4b1c4e35db" }

[profile.release]
lto = "fat"
incremental = false
codegen-units = 1
